### ISSUE TITLE
BIOS IP addresses do not propagate to boot.c

### ISSUE THREAD

**Issue by AdamMooers** [AdamMooers/upsilon#3]
The TFTP host and local ip addresses in `litex/litex/litex/soc/software/bios/boot.c` do not propagate from `local_ip` and `remote_ip` in `gateware/soc.py`. This creates a problem if the default ip addresses are not used. For example, if the local ip address is `192.168.2.50` instead of the default `192.168.1.50`, `boot.c` will still use the default.

This can be fixed by either patching `boot.c` with the correct ip addresses or by correcting the board definitions file. See `litex/litex-boards/litex_boards/targets/colorlight_i5.py` and `litex/litex-boards/litex_boards/targets/sitlinv_stlv7325.py` for an example of how to propagate these values.

**Comment by mcgoron-peter** [comment]
The `add_constants` approach seems like the correct way to do it. I fixed an earlier problem with privileged TFTP ports by passing an environment variable in the [Makefile](gateware/Makefile).

**Comment by mcgoron-peter** [comment]
This should fix it, I'll test it tonight or tomorrow morning.
https://github.com/mcgoron-peter/upsilon/blob/0bb27e9b0387fd749f8ab06a3ff93849a5f3489b/gateware/soc.py#L223
